FROM node:20-alpine

ENV CI_COMMIT_SHORT_SHA="DEVELOPMENT__MOCK__CI_COMMIT_SHORT_SHA"

ENV NODE_ENV="development"
ENV PORT=8200

RUN apk update \
  && apk add wget

WORKDIR /usr/src/app

COPY .env.compose ./

COPY tailwind.config.js postcss.config.js vite.config.mjs ./

COPY package.json tsconfig.*.json *.mjs init.sql ./

ADD src/ src/

RUN npm i
RUN npm run build

EXPOSE 8200

CMD [ "npm", "run", "start:dev" ]